module.exports = {
  schema: "src/autogenerated/schema.graphql",
  documents: ["src/**/*.tsx", "!src/gql/**/*"],
  hooks: {
    afterAllFileWrite: ["prettier --write"],
  },
  generates: {
    "src/autogenerated/gql/": {
      preset: "gql-tag-operations-preset",
    },
  },
};
