import { gql } from "@/autogenerated/gql";
import { Page } from "@/components/Page";
import { withGraphQL } from "@/graphql/urql";
import { useUrqlPoll } from "@/hooks/useUrqlPoll";
import { useQuery } from "urql";

const RandomQuery = gql(/* GraphQL */ `
  query Random {
    random
  }
`);

function Random() {
  const [{ data, fetching }, executeQuery] = useQuery({ query: RandomQuery });

  useUrqlPoll(fetching, executeQuery, 1000);

  return (
    <Page>
      <div className="p-16">{data?.random}</div>
    </Page>
  );
}

export default withGraphQL(Random);
